project_id = "uoynyjvrtuwkofeeurwh"

[auth]
enabled = true

[functions.generate-arguments]
verify_jwt = false

[functions.generate-conclusion]
verify_jwt = false

[functions.generate-tags]
verify_jwt = false